//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class catusuario
    {
        public string IdUsuario { get; set; }
        public int IdSociedad { get; set; }
        public string PassUsuario { get; set; }
        public string NomUsuario { get; set; }

        public string nomusuario { get; set; }
    }
}
